# Where VMD is installed on your system
VMDDIR=/usr/local/lib/vmd

# Location of the VMD include files vmdplugin.h and molfile_plugin.h.
# Typically, these files can be found in the subdir 
# plugins/include of the VMD installation directory.
VMDCPPFLAGS=-I$(VMDDIR)/plugins/include 

#  /usr/local/bin/h5c++ -shlib vini_cndb_runtest.c -o vini_cndb_runtest

# HDF5_CC=clang #for better warnings
CC=HDF5_CC=$(HDF5_CC) h5cc -shlib
# CC=HDF5_CC=$(HDF5_CC) /usr/local/bin/h5c++ -shlib
#compiler switches http://gcc.gnu.org/onlinedocs/gcc-3.4.3/gnat_ugn_unw/Switches-for-gcc.html
CFLAGS=-Wall -Wuninitialized -std=c99 -pedantic -fPIC
CPPFLAGS=$(VMDCPPFLAGS)
LDFLAGS=-L.
LDLIBS=
SHLD=$(CC)
SHLDFLAGS=-shared -Wl,--no-undefined $(LDFLAGS)

all: cndbtest #libcndb.so cndbplugin.so

#nasty
cndbtest: cndbtest.c cndbplugin.so libcndb.so
	$(CC) cndbtest.c -o cndbtest cndbplugin.c $(CPPFLAGS) $(CFLAGS) $(LDFLAGS) -Wl,-rpath,'\$$ORIGIN' $(HDF5LIBS) -lcndb


libcndb.so: libcndb.o
	$(SHLD) $(CFLAGS) $(SHLDFLAGS) $< -o libcndb.so $(HDF5LIBS) -lm

cndbplugin.so: cndbplugin.o libcndb.so
	$(SHLD) $(CFLAGS) $(SHLDFLAGS) $< -o cndbplugin.so $(LDLIBS) -Wl,-rpath,'\$$ORIGIN' -lcndb

check:
	cd tests && $(MAKE) check

#remove all files generated by make
clean:
	$(RM) cndbplugin.so
	$(RM) cndbtest
	$(RM) libcndb.so
	$(RM) *.o
	$(RM) *~
	$(MAKE) -C tests clean
	
# install: libcndb.so cndbplugin.so
# 	cp $^ $(VMDDIR)/plugins/LINUXAMD64/molfile/

